version: '3.8'
services:
  vue_app:
    container_name: resuelve_prueba_zero_vue_frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
      - "4000:4000"
    volumes:
      - .:/app
